import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/Common/Navbar"
import Footer from '@/components/Common/Footer'
const inter = Inter({ subsets: ['latin'] })
import { Providers } from '@/providers/provider'
import { ToastContainer } from "react-toastify";

import 'react-toastify/dist/ReactToastify.css';
export const metadata: Metadata = {
  title: 'E-Commerce',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
           <body className={inter.className}>
           <Navbar  />
         <div className=' bg-slate-300 bodypart  h-[calc(100vh-3.5rem)]  overflow-x-hidden overflow-y-scroll'>
         <main>
          {children}
          <ToastContainer/>
        </main>
        <Footer/>
        </div>
        </body>
     </Providers>
    </html>
  )
}
